version: '3'

services:
  mysql:
    image: mariadb:latest
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - '8080:80'
    restart: always
    env_file:
      - .env

    working_dir: /var/www/html
    volumes:
      - ./custom-theme:/var/www/html/wp-content/themes/custom-theme/

volumes:
  db-data: {}
